### PR TITLE
Report tile utilization with DVFS info

### PR DESCRIPTION
**Pull request by tancheng**

### CODE REVIEW

**Comment by MeowMJ** [comment]
It seems that the folder /test/kernels is only useful in ICEDdeom.py. You already have CGRA-Benchmark in your CGRA-Flow and the 'fileSource' of ICEDdemo.py can be replaced with any folder path. Do we need to keep the folder /test/kernels?

**Comment by tancheng** [comment]
Hi @HobbitQia, can u plz help take a look at the failed test? Does it look like this time the offset of 2 is unnecessary?

**Comment by HobbitQia** [comment]
> e

u r right. I checked the opcode count in line 650-660 and I thought their original opcodes are correct. So this time we should set this paramter to be 0.🤔

**Comment by HobbitQia** [comment]
I saw u change the directory names from `nonlinear_test`, `idiv_test` to `nonlinear`, `idiv`. However, the working directories we set in `cmake.yml` are still `${{github.workspace}}/test/nonlinear_test`, `${{github.workspace}}/test/idiv_test`, respectively. I think it's the reason that the github testing failed.

**Comment by tancheng** [comment]
Right, I recognized that but forgot to push my fix. Thanks!

**Pull request merged**
